name: spy_game
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-322.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.4.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  assets:
    - assets/countries.json
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  icon_size: 512
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
  